import dotenv from "dotenv";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { ROOT, formatError } from "./lib";
import { createClient, streamComplete } from "./llm";

// Make .env authoritative, same as the translation scripts.
dotenv.config({ override: true });

const PROMPTS_DIR = join(ROOT, "prompts");
const DEFAULT_SNIPPET = join(ROOT, "scripts", "fixtures", "compare-snippet.md");
const DEFAULT_OUT = join(ROOT, "output", "translate-compare.md");

const LANG_NAMES: Record<string, string> = { en: "English", ru: "Russian", uk: "Ukrainian" };

// Default candidates: the reliable, decent-quality free models from the benchmark.
const DEFAULT_MODELS = [
  "nvidia/nemotron-3-super-120b-a12b:free",
  "openai/gpt-oss-120b:free",
  "google/gemma-4-31b-it:free",
];

interface Args {
  models: string[];
  langs: string[];
  runs: number;
  file: string;
  out: string;
  concurrency: number;
  timeoutMs: number;
  retries: number;
}

function parseArgs(): Args {
  const args: Args = {
    models: DEFAULT_MODELS,
    langs: ["en", "ru", "uk"],
    runs: 2,
    file: DEFAULT_SNIPPET,
    out: DEFAULT_OUT,
    concurrency: 2,
    timeoutMs: 90_000,
    retries: 2,
  };
  for (const arg of process.argv.slice(2)) {
    if (arg.startsWith("--models=")) args.models = arg.split("=")[1].split(",").map((s) => s.trim()).filter(Boolean);
    else if (arg.startsWith("--langs=")) args.langs = arg.split("=")[1].split(",").map((s) => s.trim()).filter(Boolean);
    else if (arg.startsWith("--runs=")) args.runs = Number(arg.split("=")[1]);
    else if (arg.startsWith("--file=")) args.file = arg.split("=")[1];
    else if (arg.startsWith("--out=")) args.out = arg.split("=")[1];
    else if (arg.startsWith("--concurrency=")) args.concurrency = Number(arg.split("=")[1]);
    else if (arg.startsWith("--timeout=")) args.timeoutMs = Number(arg.split("=")[1]) * 1000;
    else if (arg.startsWith("--retries=")) args.retries = Number(arg.split("=")[1]);
  }
  return args;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

interface Cell {
  model: string;
  lang: string;
  run: number;
  ok: boolean;
  ms: number;
  text: string;
  error?: string;
}

async function translateOnce(
  client: any,
  model: string,
  lang: string,
  source: string,
  system: string,
  timeoutMs: number,
  retries: number,
): Promise<Cell> {
  const langName = LANG_NAMES[lang] || lang;
  const userMessage = `Translate the following document from Polish to ${langName}.\n\nFile: sesje.md\n\n<original>\n${source}\n</original>`;
  let lastErr = "";
  for (let attempt = 0; attempt <= retries; attempt++) {
    const started = Date.now();
    try {
      const { text } = await streamComplete({
        client,
        provider: "openrouter",
        model,
        system,
        userContent: userMessage,
        maxTokens: 4000,
        timeoutMs,
      });
      if (text.trim().length === 0) throw new Error("empty output");
      return { model, lang, run: 0, ok: true, ms: Date.now() - started, text: text.trim() };
    } catch (err: any) {
      lastErr = formatError(err);
      // Retry on transient rate-limits / timeouts; give up on hard 404s.
      if (/\b404\b/.test(lastErr) || attempt === retries) break;
      await sleep(3000);
    }
  }
  return { model, lang, run: 0, ok: false, ms: 0, text: "", error: lastErr };
}

async function runPool<T>(items: T[], concurrency: number, worker: (item: T, index: number) => Promise<void>): Promise<void> {
  let next = 0;
  async function lane() {
    while (next < items.length) {
      const i = next++;
      await worker(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, lane));
}

function render(args: Args, source: string, cells: Cell[], dateIso: string): string {
  const out: string[] = [];
  out.push("# Translation comparison — free OpenRouter models");
  out.push("");
  out.push(`Generated by \`yarn translate:compare\` on ${dateIso}. ${args.runs} run(s) per model per language, provider \`openrouter\`, real translation system prompt (\`prompts/translate.md\`), temperature 0.`);
  out.push("");
  out.push(`**Models:** ${args.models.map((m) => `\`${m}\``).join(", ")}`);
  out.push("");
  out.push("## Polish source");
  out.push("");
  out.push("```markdown");
  out.push(source.trim());
  out.push("```");

  for (const lang of args.langs) {
    out.push("");
    out.push("---");
    out.push("");
    out.push(`# ${LANG_NAMES[lang] || lang} (${lang.toUpperCase()})`);
    for (const model of args.models) {
      out.push("");
      out.push(`## \`${model}\``);
      for (let run = 1; run <= args.runs; run++) {
        const cell = cells.find((c) => c.model === model && c.lang === lang && c.run === run);
        out.push("");
        if (!cell || !cell.ok) {
          out.push(`**Run ${run}:** ❌ ${cell?.error || "no result"}`);
          continue;
        }
        out.push(`**Run ${run}** (${cell.ms} ms):`);
        out.push("");
        out.push("```markdown");
        out.push(cell.text);
        out.push("```");
      }
    }
  }
  out.push("");
  return out.join("\n");
}

async function main() {
  const args = parseArgs();

  if (!process.env.OPENROUTER_API_KEY) {
    console.error("❌ OPENROUTER_API_KEY is not set (check your .env).");
    process.exit(1);
  }

  const source = readFileSync(args.file, "utf-8");
  const system = readFileSync(join(PROMPTS_DIR, "translate.md"), "utf-8");
  const client = createClient("openrouter");

  // Build the full task list: model × lang × run.
  const tasks: { model: string; lang: string; run: number }[] = [];
  for (const model of args.models)
    for (const lang of args.langs)
      for (let run = 1; run <= args.runs; run++) tasks.push({ model, lang, run });

  console.log(`Comparing ${args.models.length} model(s) × ${args.langs.length} lang(s) × ${args.runs} run(s) = ${tasks.length} calls (concurrency ${args.concurrency})\n`);

  const cells: Cell[] = [];
  let done = 0;
  await runPool(tasks, args.concurrency, async (t) => {
    const cell = await translateOnce(client, t.model, t.lang, source, system, args.timeoutMs, args.retries);
    cell.run = t.run;
    cells.push(cell);
    done++;
    const tag = cell.ok ? `✅ ${cell.ms} ms` : `❌ ${cell.error?.slice(0, 50)}`;
    console.log(`[${done}/${tasks.length}] ${t.model}  ${t.lang.toUpperCase()} run ${t.run}  ${tag}`);
  });

  const dateIso = new Date().toISOString().slice(0, 10);
  mkdirSync(dirname(args.out), { recursive: true });
  writeFileSync(args.out, render(args, source, cells, dateIso));

  const ok = cells.filter((c) => c.ok).length;
  console.log(`\n${ok}/${cells.length} calls succeeded.`);
  console.log(`Wrote ${args.out}`);
  console.log("\nOpen that file (or ask Claude to read it) to compare translations and pick a model.");
}

main().catch((err) => {
  console.error(formatError(err));
  process.exit(1);
});
